{{- if and .Values.scheduler.enabled .Values.webUI.ingress.enabled -}}
---
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ template "dask.fullname" . }}-scheduler
  labels:
    app: "{{ template "dask.fullname" . }}-scheduler"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
{{ toYaml .Values.webUI.ingress.annotations | indent 4 }}
spec:
{{- if .Values.webUI.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.webUI.ingress.hostname | quote }}
      secretName: {{ .Values.webUI.ingress.secretName | default (printf "%s-scheduler-tls" (include "dask.fullname" .)) }}
{{- end }}
  rules:
  - {{- if ne .Values.webUI.ingress.hostname "" }}
    host: {{ .Values.webUI.ingress.hostname }}
    {{- end }}
    http:
      paths:
      - path: /
        {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
        pathType: {{ .Values.jupyter.ingress.pathType }}
        backend:
          service:
            name: {{ template "dask.fullname" . }}-jupyter
            port:
              number: {{ .Values.jupyter.servicePort }}
        {{- else }}
        backend:
          serviceName: {{ template "dask.fullname" . }}-jupyter
          servicePort: {{ .Values.jupyter.servicePort }}
        {{- end }}
{{- end -}}
